services:
  - type: web
    name: whatsapp-moderator
    env: node
    plan: free # Or your desired plan
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: GEMINI_API_KEY # Value will be set securely in the Render Dashboard
        # value: SOME_DEFAULT_VALUE # Optional: Set a default/dev value here if needed
      - key: NODE_VERSION # Optional: Specify Node version if needed
        value: 18 # Or your preferred Node version supported by Render
      # Add other environment variables if needed

# Optional: Define databases, background workers, etc.
# databases:
#   - name: my-database
#     plan: free 