services:
  - type: web
    name: whatsapp-moderator
    env: node
    plan: free # Or your desired plan
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: GEMINI_API_KEY # Value will be set securely in the Render Dashboard
        # Note: Ensure this key matches exactly what you set in Render's UI.

# Optional: Define databases, background workers, etc.
# databases:
#   - name: my-database
#     plan: free 