services:
  - type: worker
    name: whatsapp-moderator
    env: node
    plan: free # Or your desired plan
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Value will be set securely in the Render Dashboard
      - key: NODE_VERSION # Optional: Specify Node version if needed
        value: 18 # Or your preferred Node version supported by Render

# Optional: Define databases, background workers, etc.
# databases:
#   - name: my-database
#     plan: free 